import {
  Menu,
  X,
  Home,
  Book,
  Compass,
  Info,
  LogIn,
  UserPlus,
  ChevronRight,
  Calculator,
  Atom,
  FlaskConical,
  Dna,
  Landmark,
  Monitor,
  Newspaper,
  Clipboard,
  Globe,
  Languages,
  Palette,
  TrendingUp,
  Code,
  Briefcase,
  GraduationCap,
  Brain,
  BookOpen,
  Video,
  Headphones,
  FileText,
  Trophy,
  Download,
} from "lucide-react";

export const subjects = [
  {
    name: "Mathematics",
    icon: Calculator,
    description: "Algebra, Calculus, Statistics",
  },
  {
    name: "Physics",
    icon: Atom,
    description: "Mechanics, Thermodynamics, Quantum",
  },
  {
    name: "Chemistry",
    icon: FlaskConical,
    description: "Organic, Inorganic, Physical",
  },
  {
    name: "Biology",
    icon: Dna,
    description: "Genetics, Ecology, Human Biology",
  },
  {
    name: "History",
    icon: Landmark,
    description: "World History, Ancient Civilizations",
  },
  { name: "Geography", icon: Globe, description: "Physical & Human Geography" },
  {
    name: "Languages",
    icon: Languages,
    description: "English, Spanish, French",
  },
  { name: "Arts", icon: Palette, description: "Visual Arts, Music, Drama" },
  {
    name: "Economics",
    icon: TrendingUp,
    description: "Micro & Macro Economics",
  },
  {
    name: "Computer Science",
    icon: Code,
    description: "Programming, Algorithms, Data",
  },
  {
    name: "Business",
    icon: Briefcase,
    description: "Management, Marketing, Finance",
  },
  {
    name: "Psychology",
    icon: Brain,
    description: "Cognitive, Social Psychology",
  },
];

export const browses = [
  {
    name: "Courses",
    icon: GraduationCap,
    description: "Full structured courses",
    count: "200+",
  },
  {
    name: "Tutorials",
    icon: Monitor,
    description: "Step-by-step guides",
    count: "500+",
  },
  {
    name: "Articles",
    icon: Newspaper,
    description: "In-depth articles",
    count: "1000+",
  },
  {
    name: "Quizzes",
    icon: Clipboard,
    description: "Practice tests & quizzes",
    count: "300+",
  },
  {
    name: "Videos",
    icon: Video,
    description: "Educational videos",
    count: "800+",
  },
  {
    name: "Podcasts",
    icon: Headphones,
    description: "Audio learning content",
    count: "150+",
  },
  {
    name: "Study Guides",
    icon: BookOpen,
    description: "Comprehensive study materials",
    count: "400+",
  },
  {
    name: "Worksheets",
    icon: FileText,
    description: "Printable worksheets",
    count: "600+",
  },
  {
    name: "Competitions",
    icon: Trophy,
    description: "Academic competitions",
    count: "50+",
  },
  {
    name: "Resources",
    icon: Download,
    description: "Downloadable resources",
    count: "1200+",
  },
];
